[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.6.0"

[[constraint]]
  name = "github.com/gogo/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "1.0.0"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "1.11.3"

[[constraint]]
  name = "gopkg.in/square/go-jose.v2"
  version = "2.1.6"

[[constraint]]
  name = "zvelo.io/httpsig"
  version = "1.1.4"

[[constraint]]
  name = "zvelo.io/msg"
  version = "~1.13.3"

[[override]]
  name = "github.com/graph-gophers/graphql-go"
  branch = "master"

[[override]]
  name = "github.com/opentracing/opentracing-go"
  branch = "master"
